version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - today-v3-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - today-v3-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: make ci.setup
      - run:
          name: Run unit tests
          command: make ci.test-unit
      - run:
          name: Install executable
          command: make ci.install
      - save_cache:
          name: Cache Dependencies
          key: today-v3-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - persist_to_workspace:
          root: ~/.local
          paths: bin
  integration-tests:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - attach_workspace:
          at: ~/.local
      - run:
          name: Run Integration tests
          command: make ci.test-integration
      - store_artifacts:
          path: ~/.local/bin/today
          destination: today
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - integration-tests:
          requires:
            - build
