version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - today-v3-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - today-v3-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run tests
          command: stack --no-terminal test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - save_cache:
          name: Cache Dependencies
          key: today-v3-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          path: ~/.local/bin/today
          destination: today
      - persist_to_workspace:
          root: ~/.local
          paths: bin
  integration-tests:
    docker:
      - image: fpco/stack-build-small:lts
    steps:
      - checkout
      - run:
          name: Install Bats
          command: |
            git clone https://github.com/bats-core/bats-core.git
            cd bats-core
            ./install.sh /usr/local
      - attach_workspace:
          at: ~/.local
      - run:
          name: Integration tests
          command: bats test/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - integration-tests:
          requires:
            - build
